apiVersion: v1
appVersion: "0.0.25"
description: A Helm chart to create GNES for Kubernetes
name: gnes
version: 0.1.0
home: https://gnes.ai/
icon: https://gnes.ai/img/gnes-logo-tight.svg
maintainers:
  - name: gnes_team
    email: team@gnes.ai
