apiVersion: v1
kind: Service
metadata:
  name: {{ template "gnes.frontend.fullname" . }}
  labels:
    app: {{ template "gnes.name" . }}
    component: "frontend"
    chart: {{ template "gnes.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.frontend.service_type }}
  ports:
    - name: grpc
      port: {{ .Values.frontend.grpc_port }}
      nodePort: {{ .Values.frontend.nodePort }}
      targetPort: grpc-port
    - name: grpc-out
      port: {{ .Values.frontend.port_out }}
      targetPort: frontend-out
  selector:
    app: "{{ template "gnes.name" . }}"
    component: "frontend"
    release: "{{ .Release.Name }}"