apiVersion: v1
kind: Service
metadata:
  name: {{ template "gnes.frontend.fullname" . }}
  labels:
    app: {{ template "gnes.name" . }}
    component: "frontend"
    chart: {{ template "gnes.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      {{- if contains "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - port: {{ .Values.frontend.port_out }}
      targetPort: frontend-out
  selector:
    app: "{{ template "gnes.name" . }}"
    component: "frontend"
    release: "{{ .Release.Name }}"